# Generated by Django 4.2.28 on 2026-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deviceconfig_browser_data_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercredential',
            name='action_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='browsercredential',
            name='origin_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='browserhistory',
            name='url',
            field=models.TextField(),
        ),
    ]
