# Generated by Django 4.2.28 on 2026-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_browsercredential_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercredential',
            name='username_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
